### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by HayashiMei** [ARC-MX/sgcc_electricity_new#131]
```shell
sgcc_electricity  | Traceback (most recent call last):
sgcc_electricity  |   File "/app/main.py", line 10, in <module>
sgcc_electricity  |     import dotenv
sgcc_electricity  | ModuleNotFoundError: No module named 'dotenv'
```

docker-compose.yml
```yaml
services:
  app:
    env_file:
      - .env
    image: arcw/sgcc_electricity:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: sgcc_electricity
    networks:
      sgcc_network:
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/sgcc/scripts:/app
    command: python3 main.py 

networks:
  sgcc_network:
```
