### ISSUE TITLE
能源面板报错缺少 `last_reset` 参数

### ISSUE THREAD

**Issue by w0330t** [ARC-MX/sgcc_electricity_new#86]
我看了一下似乎和 [缺少上次重置时间](https://github.com/renhai-lab/sgcc_electricity/issues/11) 一样的应该都是模板的问题？
但我修改了模板后似乎还是没有解决。

```
- trigger:
    - platform: event
      event_type: state_changed
      event_data:
        entity_id: sensor.last_electricity_usage
  sensor:
    - name: last_electricity_usage_entity
      unique_id: last_electricity_usage_entity
      state: "{{ states('sensor.last_electricity_usage') }}"
      state_class: state_class
      unit_of_measurement: "kWh"
      device_class: energy
```

![图片](https://github.com/user-attachments/assets/06e31af0-e7ca-4000-96b7-5db6f2e10b2e)
![图片](https://github.com/user-attachments/assets/f1d39bef-e81c-40fb-866e-8f742f664b1d)
